spring.application.name=fraudscore-back
server.address=0.0.0.0
server.port=5000
spring.mongodb.uri=mongodb+srv://root:root@cluster0.vqwpuuj.mongodb.net/?appName=cluster0
spring.mongodb.username=root
spring.mongodb.password=root
spring.mongodb.database=fraudscore

turnstile.secret = 0x4AAAAAACKpIzTx27slPJpfQ3m05RNz3fE
jwt.token = AzT2Zpa8oD8K9yVfxgJbzYDRTkzfwpAMpUX5JJbuE67TEv04ebGCSLfh4_NupPoP

upload.path=uploads



spring.ai.openai.api-key=zk5A4obB.77qiiCcuR6e0BvON1EJrvv3mnRe4obOS

spring.ai.openai.base-url=https://inference.baseten.co/v1

spring.ai.openai.chat.options.model=openai/gpt-oss-120b
spring.ai.openai.chat.options.http-headers.Authorization= zk5A4obB.77qiiCcuR6e0BvON1EJrvv3mnRe4obOS

spring.ai.openai.chat.options.temperature=1
spring.ai.openai.chat.options.top-p=1
spring.ai.openai.chat.options.max-tokens=3000
spring.ai.openai.chat.options.presence-penalty=0
spring.ai.openai.chat.options.frequency-penalty=0